include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    avoid_positional_boolean_parameters: false
    type_annotate_public_apis: false
    public_member_api_docs: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore
